### ISSUE TITLE
GitHub login option fails

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/buildbotics-ui#51] opened 2015-03-08 17:44 UTC
When I select the GitHub option for logging in and I'm already logged in at GitHub, it fails with an error message that says: DB:1644: Name cannot be empty

When I select the GitHub option and I am not logged in, I get prompted to log in at GitHub.  Then it fails and if I hit the back button, I go to my account on GitHub rather than back to Buildbotics.

**Comment by jcoffland** [comment] 2015-03-08 22:15
Thought I had fixed this.  This is a duplicate of issue #30.

**Closed as completed by jcoffland** 2015-03-08 22:15 UTC
