### ISSUE TITLE
License displays incorrectly in some circumstances

### ISSUE THREAD

**Issue by scofflan** [buildbotics/buildbotics-ui#24] opened 2015-01-29 20:11 UTC
If looking at Doug's project Buildbotics_logo does states 

"Permission to use the contents of this project is granted by Doug under the terms of the ."

I'm guessing this is due to no license choice selected.

**Comment by jcoffland** [comment] 2015-01-29 22:00
This is a duplicate of #13.

**Closed as completed by jcoffland** 2015-01-29 22:00 UTC
