### ISSUE TITLE
Partially uploaded files still present in file manager but not downloadable.

### ISSUE THREAD

**Issue by scofflan** [buildbotics/buildbotics-ui#16] opened 2015-01-27 14:21 UTC
After attempting to download a rather large file 3.4MB it stalled and then stopped when retreiving it from Amazon S3 storage. Attempts to down this or other file after this returned a 403 error. 
Files continued to upload correctly but could not be retrived.

**Comment by scofflan** [comment] 2015-01-27 14:33
After waiting a few minute the small file are now avaiable. Perhaps the large file is choking the connection to the Amazon static file storage?

**Comment by jcoffland** [comment] 2015-01-27 17:02
I'm not sure I understand what went on here.  Can you reproduce it?

Sounds like at the very least I need to make the upload process more clear.

**Comment by scofflan** [comment] 2015-01-27 17:18
I think this is just an issue of files are not immediately available for download and when uploading files there are available in the order they were uploaded.
So if I upload files as follows
1. test.jpg 30k (available in 5-10s)
2. large.jpg 4M (avaialble in 2m after file 1 is ready)
3. small.jpg 45k ( available in 5-10s after file 2 is ready)

This could be problematic if static files are queing on the media storage and many users are uploading file simultaneously. You might have a processing or transfer limit on your Amazon S3 account. Limiting file size and or a file conversion utility might be helpful.

**Comment by scofflan** [comment] 2015-01-27 17:22
Hmmm there is something odd about this. I can view the files now after logging out and then back in to the site. 
In trying to reproduce this error I uploaded another large file logged out and then clicked on the file while logged out. and receive the following error

This XML file does not appear to have any style information associated with it. The document tree is shown below.

'
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>F2614B6DBC8C517A</RequestId>
<HostId>
uo+TLwsPO4kIF6ylBSOanF4O1LosqdSyIgKjTcyxJC7rm8Z/hMAKFtKeDEWznufI
</HostId>
</Error>
'

I get the same thing once I have logged back in and try to view the file

**Comment by scofflan** [comment] 2015-01-28 01:01
The following image still shows an XML error when trying to view it. 

https://buildbotics.s3.amazonaws.com/2wg0x__AmU34swiuM9nLYr8cIY5EdbHXS7VIihVgzWcA/6

**Comment by jcoffland** [comment] 2015-01-28 08:28
That's intentional.  You cannot download the file directly from S3.  You have to ask for the file with a URL like this:

```
https://buildbotics.com/<user>/<project>/<filename>
```

Buildbotics then generates a signed URL to the S3 resource and redirects the request to it.  The signed URL is only good for a few minutes.  This is to keep people from using it as free disk space.

**Comment by jcoffland** [comment] 2015-01-28 08:34
It looks like the file at:

```
https://test.buildbotics.com/sam.coffland/Test_project/6%20mos%20kate%20with%20book.JPG
```

is not really on S3 but is in the buildbotics DB.  I suspect the upload was started, which created an entry in the DB, but was not completed.  S3 does not keep partial files.  I need to rethink the logic here.

There is a way to listen to events from S3.  A process could be setup which does this and updates the buildbotics DB when files uploads are confirmed. (buildbotics/buildbotics/issues/5)

**Comment by jcoffland** [comment] 2015-01-28 10:18
Turns out I was wrong.  The file was uploaded to S3.  The problem was that the file name part of the URL in the DB was not URL encoded.  This one failed because it has spaces in the file name.  It works now.

**Comment by jcoffland** [comment] 2015-01-28 10:24
Should be fixed now.

**Closed as completed by jcoffland** 2015-01-28 10:24 UTC
Labels: bug
